services:
  postgresql:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BackEnd
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: flask_app
    image: proyectofinalarquidesoftware-app:${APP_VERSION:-1.1}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:BackEnd@postgresql:5432/postgres
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "5050:5050"

volumes:
  postgres_data:
